%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ENPM 673 Perception For Autonomous Robotics
% PROJECT 3  - Spring 2018
%
% Question Part 0 (10 points)- Buoy Detection 
%
% This function read the cropped buoy images that are generated by the
% function named 'Buoy_Extraction' and generates Histogram plot for each
% colored Buoy. Also it returns the Buoy Images in the form of a cell
% containing arrays of each colored buoy images. 
% [colorSamples] = [red,green,yellow]
% 
% 
% Code By: Mayank Pathak
%          115555037
%
% Dependencies: This code uses four function, namely
% 'readCroppedfiles','readmultifiles','hist_Plot','average_colorHist'.
% Later two are defined in this file itself.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [colorSamples] = averageHistogram(~)

close all
% Create color Samples from Buoy images
[red,green,yellow] = readmultifiles;

% Cropped Buoy images for eliminating black background
[Cred,Cgreen,Cyellow] = readCroppedfiles;

% Threshold for filtering colors
tred = 20;
tgreen = -45;
tyellow = 50;

Redbouy = labred(red,tred);
Greenbouy = labgreen(green,tgreen);
Yellowbouy = labyellow(yellow,tyellow);
allbouy = {Redbouy,Greenbouy,Yellowbouy}; 

distribution_Plot(Redbouy,'red')
distribution_Plot(Greenbouy,'green')
distribution_Plot(Yellowbouy,'yellow')

colorSamples = allbouy;

average_colorHist(Cred,'red');
average_colorHist(Cgreen,'green');
average_colorHist(Cyellow,'yellow');

end

%% for plotting 3D color distribution
function distribution_Plot(Bouy,color)

writeFolder = '../../ColorSeg/Outputs/Part0';
fileName = [color,'_hist'];
color = ['.',color];
rr = Bouy(:,1);
gg = Bouy(:,2);
bb = Bouy(:,3);
fig1 = figure;
plot3(rr,gg,bb,color)
filename = fullfile(writeFolder,fileName);
saveas(fig1, filename,'jpg')
end

%% For Plotting average Color Histogram
function average_colorHist(colorcell,color)

[~,c] = size(colorcell);
tr = zeros(256,1);
tg = zeros(256,1);
tb = zeros(256,1);

    for i = 1:c
        imgrgb = cell2mat(colorcell(i));
        Red = imgrgb(:,:,1);
        Green = imgrgb(:,:,2);
        Blue = imgrgb(:,:,3);

        [yRed, x1] = imhist(Red);
        [yGreen, x2] = imhist(Green);
        [yBlue, x3] = imhist(Blue);
     
        
        
        tr = tr + yRed;
        tg = tg + yGreen;
        tb = tb + yBlue;

    end

    tr = tr/c;
    tg = tg/c;
    tb = tb/c;
    fig1 = figure;
    plot(x1,tr,'Red', x2, tg, 'Green', x3, tb, 'Blue');
  
    hold on
    if strcmp(color,'red') == 1
        hold on 
        fitti = fit(x1,tr,'gauss2');
        plot(fitti,x2,tr,'k')
        title('For Red')
    end
    if strcmp(color,'green') == 1
        fitti = fit(x2,tg,'gauss2');
        plot(fitti,'k'); %x2,tg,'.green')
        title('For Green')
    end
    if strcmp(color,'yellow') == 1
        ty = (tg + tr)/2;
        fitti = fit(x2,ty,'gauss2');
        plot(fitti,'k');%,x2,ty,'.yellow')
        title('For Yellow')
    end
    
    filename = ['../../ColorSeg/Outputs/Part0/',color,'_hist'];
    saveas(fig1,filename,'jpg');
    
end
